name: trigger appium tests
run-name: ${{github.actor}} has triggered the workflow
on: [push]
jobs:
  run-mobile-tests:
    runs-on: macos-latest
    steps:
      - name: setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Pull the codebase in the test runner
        uses: actions/checkout@v3

      - name: Setup appium
        run: |
          npm i --location=global appium
          appium --version
      - name: Setup Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          script: mvn clean test